version: "3.4"
networks:
  proxylampy:
    external: true
  serverlampy:
    external: true
  net:
    driver: overlay
    attachable: true
services:
  phpfpm:
    image: koromerzhin/php:8.4.3-apache
    depends_on:
      - mariadb
      - mercure
      - mailhog
      - redis
    volumes:
      - ${PWD}/apps:/var/www/:rw
      - ${PWD}/conf/php.ini-development://usr/local/etc/php/conf.d/php.ini
    environnement:
      - APACHE_DOCUMENT_ROOT=/var/www/web
    networks:
      - net
      - serverlampy
      - proxylampy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.drupal.rule=Host(`drupal.traefik.me`)"
        - "traefik.http.routers.drupal-tls.tls.domains[0].main=drupal.traefik.me"
        - "traefik.http.routers.drupal.tls=true"
        - "traefik.http.services.drupal.loadbalancer.server.port=80"